[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to handle CORS during development
[[redirects]]
  from = "/api/*"
  to = "https://expense-tracker-uhoh.onrender.com/api/:splat"
  status = 200
  force = false 